### ISSUE TITLE
Fix a few bugs/address certain features for Lightcurve plots

### ISSUE THREAD

**Issue by jchate6** [LCOGT/neoexchange#522]
- [x] Bessel Filters Lower case in Table
- [ ] Automated `lc_extraction` fails for cadences after first attempt
- [x] print upload final uploadfile path from `lc_extraction`
- [x] upload data should give warning if S3 != True
- [x] Compile gif for composite cadence
- [x] Plot title should update with data included
- [x] Fix long titles on png plots
- [x] Large cadences cause matplotlib issues: 
```home/jchatelain/git/neoexchange/neoexchange/photometrics/gf_movie.py:161: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig = plt.figure()```

**Comment by talister** [comment]
Can I add another minor nit: the title in long cadences with many sites can go off the plot edges. Not sure how easy it would be to detect and add a linebreak ?

**Comment by jchate6** [comment]
> Can I add another minor nit: the title in long cadences with many sites can go off the plot edges. Not sure how easy it would be to detect and add a linebreak ?

Which plot?

**Comment by jchate6** [comment]
> > Can I add another minor nit: the title in long cadences with many sites can go off the plot edges. Not sure how easy it would be to detect and add a linebreak ?
> 
> Which plot?

Ah, like `99942_sin_20210211_1144746_lightcurve_cond.png` ?
I think we should have a larger discussion on the purpose of our various generated plots.

**Comment by talister** [comment]
> > > Can I add another minor nit: the title in long cadences with many sites can go off the plot edges. Not sure how easy it would be to detect and add a linebreak ?
> > 
> > 
> > Which plot?
> 
> Ah, like `99942_sin_20210211_1144746_lightcurve_cond.png` ?
> I think we should have a larger discussion on the purpose of our various generated plots.

How did you guess... ? ;-) Fair enough, punt it for now...
