### ISSUE TITLE
Add dithering support to NEOexchange

### ISSUE THREAD

**Issue by talister** [LCOGT/neoexchange#565]
As a LOOK observer of extended fuzzy things, I would like NEOexchange to support submitting dithered observations

**Comment by mkelley** [comment]
What I like to do is specify the scale and pattern., e.g., a 6-point (hexagonal) pattern with 20" step sizes.  There's some fun patterns in the JWST docs: https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-operations/nircam-dithers-and-mosaics/nircam-subpixel-dithers/nircam-standard-subpixel-dithers

**Comment by jchate6** [comment]
Finally, all of the above implementation ideas assume trying to integrate dithering into the current scheduling form on Neoexchange. We COULD treat dithering more like cadence and give it an entirely separate treatment where we replace slot length with "length of dither" and add more complex dither options than would be feasible in the standard form.
