### ISSUE TITLE
Comets (obviously) break the orbit plotter

### ISSUE THREAD

**Issue by jchate6** [LCOGT/neoexchange#575]
see https://rollbar.com/LCO/NEOexchange/items/234/?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification

specifically, this break happens when we try to set the plot bounds using semi-major axis, but I'd bet it breaks elsewhere too...

**Comment by talister** [comment]
All comets or just long period/e>=1 ones ? Does 67P work for example ?

**Comment by jchate6** [comment]
anything with comet elements at the moment
