### ISSUE TITLE
Add current user to SuperBlock

### ISSUE THREAD

**Issue by zemogle** [LCOGT/neoexchange#608]
Log the observer's username in SuperBlock. This info is available in the FITS headers, so we could potentially backfill past SuperBlocks.

**Comment by zemogle** [comment]
Instead of making this a field on the SuperBlock model, I've made it an extra model, a little like a many to many model. There are 2 advantages:
1. We don't have to create a new column which will be blank for all the past Superblocks
2. We can have multiple observers, if for example we manually combined blocks submitted by different people.

**Comment by talister** [comment]
Deployed
