### ISSUE TITLE
GIF movies now have excess whitespace around image

### ISSUE THREAD

**Issue by talister** [LCOGT/neoexchange#610]
With the change in https://github.com/LCOGT/neoexchange/commit/ddaee0047354617da0caff03d8077603fe077d8d on `feature/lightcurve_converter` to make the GIF movies work on Matplotlib > 3.4, we now have an excess amount of whitespace at the top of movies compared to the older version (`matplotlib<3.3`) that is pinned on `main`. Screen shots of "old" (from `20220721/65803_2947583_framemovie.gif`) and "new" (from `20221002/65803_3015270_framemovie.gif`) attached

![gifmovie_old](https://user-images.githubusercontent.com/1776252/193698454-1dfbc098-668a-40f0-9d3c-1ad6b030e98a.png)
![gifmovie_new](https://user-images.githubusercontent.com/1776252/193698457-3572dc89-7abc-4075-8750-486c84eacbb9.png)

**Comment by jchate6** [comment]
Look at that tail...

**Comment by talister** [comment]
> Look at that tail...

While I am not sure I should be encouraging this, there are deeper multicolor tail data in https://observe.lco.global/requests/3015287 when I put in a gri sequence to see if the scheduler was working when it was looking empty yesterday afternoon

**Comment by jchate6** [comment]
How does this look?
![2022AB_2762138_framemovie](https://user-images.githubusercontent.com/32683393/193941126-6126b761-6f27-4e78-8d4d-63f9f4ee7773.gif)

I'm having issues getting `pyslalib.slalib` working so I can't do a proper test with grid lines and axes it seems, and not having it makes all of the 
```
try:
    import pyslalib.slalib as S
except:
    pass
 ```
 statements deceptively successful.

**Comment by jchate6** [comment]
The method that sup_titles get applied and default axes scaling was changed. 
The size is a little different, but I don't think it's bad. I can make it bigger if you like.

**Comment by jchate6** [comment]
I also learned about the very interesting[ astropy.Time](https://docs.astropy.org/en/stable/time/index.html) package...

**Comment by jchate6** [comment]
Update:
the `gca(projection=wcs)` that applies the moving grid is also breaking in [matplotlib 3.4.0](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.4.0.html#changes-to-behavior-of-axes-creation-methods-gca-add-axes-add-subplot).

Looking for a work around.

**Comment by talister** [comment]
> Update: the `gca(projection=wcs)` that applies the moving grid is also breaking in [matplotlib 3.4.0](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.4.0.html#changes-to-behavior-of-axes-creation-methods-gca-add-axes-add-subplot).
> 
> Looking for a work around.

I fixed that in this commit: https://github.com/LCOGT/neoexchange/commit/ddaee0047354617da0caff03d8077603fe077d8d

**Comment by jchate6** [comment]
oh neat.

**Comment by talister** [comment]
> The method that sup_titles get applied and default axes scaling was changed. The size is a little different, but I don't think it's bad. I can make it bigger if you like.

That looks a lot better. What would help the most for the Didymos observations would if the secondary title include the frame number (the `0xyz` out of the middle of the filename). When clipping the output photometry, I only have a filename and JD available so matching with the frame in the animation is harder...

**Comment by talister** [comment]
> oh neat.

They did a bit of a dirty on us... If you remove the over-zealous `warnings`-ignoring in our code, it says what we were doing was deprecated in 3.4 and would fail after 2 minor releases. We're on 3.5.x something so within that, unless they meant 3.4.1 and 3.4.2 and then break...

**Comment by jchate6** [comment]
I was not in the right branch for that test.
Results:
![2022AB_2762138_framemovie](https://user-images.githubusercontent.com/32683393/193948005-3ef67ee2-5000-43f7-b2b7-885cfd8d2bf3.gif)

**Comment by jchate6** [comment]
easy:
![2022AB_2762138_framemovie](https://user-images.githubusercontent.com/32683393/194119745-a993b356-d8d0-4e45-9a53-c33fb6eeddf2.gif)

**Comment by jchate6** [comment]
![2022AB_2762138_framemovie](https://user-images.githubusercontent.com/32683393/194127314-4e0d6f6c-3805-401d-a06b-906d96491d41.gif)

**Comment by jchate6** [comment]
Slightly different format. Maybe cleaner?
![2022AB_2762138_framemovie](https://user-images.githubusercontent.com/32683393/194127608-49b90ff8-eefa-4e0b-b8c8-3015b41f1ce0.gif)

**Comment by jchate6** [comment]
Oh that's interesting. That code is the same...
![2022AB_2762138_framemovie](https://user-images.githubusercontent.com/32683393/194134461-da40320e-a5ae-444b-a156-84a5274b6387.gif)

**Comment by talister** [comment]
> Oh that's interesting. That code is the same... ![2022AB_2762138_framemovie](https://user-images.githubusercontent.com/32683393/194134461-da40320e-a5ae-444b-a156-84a5274b6387.gif) [ ![2022AB_2762138_framemovie](https://user-images.githubusercontent.com/32683393/194134461-da40320e-a5ae-444b-a156-84a5274b6387.gif) ](https://user-images.githubusercontent.com/32683393/194134461-da40320e-a5ae-444b-a156-84a5274b6387.gif) [ ](https://user-images.githubusercontent.com/32683393/194134461-da40320e-a5ae-444b-a156-84a5274b6387.gif)

Why does stuff silently change in the background when you don't alter the code... !? sigh

**Comment by talister** [comment]
> I know the `%x` and `%X` uses assumptions about local time formats, but I'm not sure why that would be different here.

Probably server doesn't have a `LOCALE` set (or a generic one) and locally it has "America" or "Pacific/Los Angeles" timezone or some such

**Comment by jchate6** [comment]
better to just be explicit.
