### ISSUE TITLE
Examine and determine need to update MuSCAT configs options

### ISSUE THREAD

**Issue by talister** [LCOGT/neoexchange#625]
The diffusers (which we don't use) options for MuSCAT 3 and the upcoming MuSCAT 4 are being replaced with narrowband filters and the API submit language will change. Per @drhaz:
```
The optical elements definition will change the naming from diff(us)er_{filter}position to narrowband_{filter}_position.
```
We should assess and update the MuSCAT-specific submit code in `sources_subs.py`

**Comment by carrholt** [comment]
fixed and deployed as 3.13.4
