### ISSUE TITLE
Lost access to Advanced Options when scheduling observations

### ISSUE THREAD

**Issue by mkelley** [LCOGT/neoexchange#629]
I'm not able to open up the Advanced Options on the confirm scheduling page.  I selected it once and it flashed open for a split second, but the page was in the middle of a reload after selecting Update Parameters.  The page refreshed and I've not been able to open it since.  I cleared my browser cache and cookies, and also used another computer, but the issue remains (linux+Chrome on both accounts).  There is an error on the Javascript console:
```
Uncaught TypeError: Cannot read properties of null (reading 'checked')
    at HTMLDocument.<anonymous> (cadence/:61:11)
    at e (jquery.min.js:2:26990)
    at t (jquery.min.js:2:27292)
```
It is unclear to me if this is related.

I've also tried linux+Firefox, but still cannot open the Advanced Options.  The JS console error there is:
```
Uncaught TypeError: ws is null
    <anonymous> https://neoexchange.lco.global/schedule/108003/confirm/:61
    jQuery 2
```

**Comment by mkelley** [comment]
I think the last time I scheduled observations was Sep 30, so two minor versions ago.

**Comment by talister** [comment]
The last changes to the jQuery-importing code was mid-August in commit [ab21b79d27b](https://github.com/LCOGT/neoexchange/commit/ab21b79d27b43a6b2891388c51f5c07a36efe347) as part of Issue #623 and there was related fall out in Issue #624 when I asked @zemogle if he could fix the off-screen/unclickable post-scheduling message I was getting on Windows+Firefox.
So if it was working for you on Sep 30 then this timing doesn't line up but still seems connected to the jQuery version change although it may be something else that was triggered when Carrie deployed the new 3.13.4 to AWS and it pulled in something different as part of the build/deploy...

**Comment by mkelley** [comment]
Tried scheduling a new object today, and the options open as they should.  <shrug>

**Comment by talister** [comment]
> Tried scheduling a new object today, and the options open as they should.

Yay...and simultaneously Not Yay... How I Hate Heisenbugs...

**Comment by carrholt** [comment]
Closing for now as can't replicate; feel free to reopen if it reoccurs.
